export interface City {
  id: string;
  name: string;
  x: number;
  y: number;
}

export interface Route {
  id: string;
  cities: [string, string];
  length: number;
  color: string;
  double?: boolean;
  isTunnel?: boolean;
  isFerry?: boolean;
}

export interface MapData {
  id: string;
  name: string;
  viewBox: string;
  cities: City[];
  routes: Route[];
}

export const EUROPE_MAP: MapData = {
  id: 'europe',
  name: 'Europe Edition',
  viewBox: '0 0 1000 1000',
  cities: [
    { id: 'edinburgh', name: 'Edinburgh', x: 150, y: 80 },
    { id: 'london', name: 'London', x: 210, y: 280 },
    { id: 'amsterdam', name: 'Amsterdam', x: 310, y: 280 },
    { id: 'paris', x: 250, y: 460, name: 'Paris' },
    { id: 'brest', x: 120, y: 460, name: 'Brest' },
    { id: 'dieppe', x: 160, y: 400, name: 'Dieppe' },
    { id: 'bruxelles', x: 310, y: 330, name: 'Bruxelles' },
    { id: 'essen', x: 380, y: 300, name: 'Essen' },
    { id: 'frankfurt', x: 380, y: 400, name: 'Frankfurt' },
    { id: 'berlin', x: 480, y: 320, name: 'Berlin' },
    { id: 'danzig', x: 580, y: 250, name: 'Danzig' },
    { id: 'kobenhavn', x: 450, y: 180, name: 'Kobenhavn' },
    { id: 'stockholm', x: 550, y: 80, name: 'Stockholm' },
    { id: 'petrograd', x: 850, y: 80, name: 'Petrograd' },
    { id: 'riga', x: 650, y: 150, name: 'Riga' },
    { id: 'wilno', x: 720, y: 250, name: 'Wilno' },
    { id: 'warszawa', x: 650, y: 350, name: 'Warszawa' },
    { id: 'kyiv', x: 820, y: 400, name: 'Kyiv' },
    { id: 'moskva', x: 920, y: 280, name: 'Moskva' },
    { id: 'kharkov', x: 920, y: 450, name: 'Kharkov' },
    { id: 'rostov', x: 920, y: 550, name: 'Rostov' },
    { id: 'sochi', x: 950, y: 700, name: 'Sochi' },
    { id: 'sevastopol', x: 820, y: 700, name: 'Sevastopol' },
    { id: 'bucuresti', x: 750, y: 650, name: 'Bucuresti' },
    { id: 'budapest', x: 620, y: 550, name: 'Budapest' },
    { id: 'wien', x: 550, y: 500, name: 'Wien' },
    { id: 'munchen', x: 450, y: 480, name: 'Munchen' },
    { id: 'zurich', x: 380, y: 550, name: 'Zurich' },
    { id: 'venezia', x: 480, y: 620, name: 'Venezia' },
    { id: 'roma', x: 450, y: 780, name: 'Roma' },
    { id: 'brindisi', x: 550, y: 850, name: 'Brindisi' },
    { id: 'palermo', x: 450, y: 920, name: 'Palermo' },
    { id: 'athina', x: 650, y: 900, name: 'Athina' },
    { id: 'constantinople', x: 780, y: 820, name: 'Constantinople' },
    { id: 'smyrna', x: 750, y: 920, name: 'Smyrna' },
    { id: 'angora', x: 850, y: 920, name: 'Angora' },
    { id: 'erzurum', x: 950, y: 880, name: 'Erzurum' },
    { id: 'sofia', x: 680, y: 750, name: 'Sofia' },
    { id: 'sarajevo', x: 580, y: 720, name: 'Sarajevo' },
    { id: 'zagrab', x: 550, y: 650, name: 'Zagrab' },
    { id: 'marseille', x: 320, y: 720, name: 'Marseille' },
    { id: 'pamplona', x: 180, y: 700, name: 'Pamplona' },
    { id: 'madrid', x: 80, y: 820, name: 'Madrid' },
    { id: 'lisbon', x: 40, y: 900, name: 'Lisbon' },
    { id: 'cadiz', x: 100, y: 950, name: 'Cadiz' },
    { id: 'barcelona', x: 220, y: 850, name: 'Barcelona' },
  ],
  routes: [
    { id: 'edi-lon-1', cities: ['edinburgh', 'london'], length: 4, color: 'black' },
    { id: 'edi-lon-2', cities: ['edinburgh', 'london'], length: 4, color: 'orange', double: true },
    { id: 'lon-die', cities: ['london', 'dieppe'], length: 2, color: 'gray', isFerry: true },
    { id: 'lon-die-2', cities: ['london', 'dieppe'], length: 2, color: 'gray', isFerry: true, double: true },
    { id: 'lon-ams', cities: ['london', 'amsterdam'], length: 2, color: 'gray', isFerry: true },
    { id: 'ams-ess', cities: ['amsterdam', 'essen'], length: 3, color: 'yellow' },
    { id: 'ams-bru', cities: ['amsterdam', 'bruxelles'], length: 1, color: 'black' },
    { id: 'bru-die', cities: ['bruxelles', 'dieppe'], length: 2, color: 'green' },
    { id: 'bru-fra', cities: ['bruxelles', 'frankfurt'], length: 2, color: 'blue' },
    { id: 'die-bre', cities: ['dieppe', 'brest'], length: 2, color: 'orange' },
    { id: 'die-par', cities: ['dieppe', 'paris'], length: 1, color: 'pink' },
    { id: 'bre-par', cities: ['brest', 'paris'], length: 3, color: 'black' },
    { id: 'bre-pam', cities: ['brest', 'pamplona'], length: 4, color: 'pink' },
    { id: 'par-pam-1', cities: ['paris', 'pamplona'], length: 4, color: 'blue' },
    { id: 'par-pam-2', cities: ['paris', 'pamplona'], length: 4, color: 'green', double: true },
    { id: 'par-mar', cities: ['paris', 'marseille'], length: 4, color: 'white' },
    { id: 'par-bru', cities: ['paris', 'bruxelles'], length: 2, color: 'yellow' },
    { id: 'par-bru-2', cities: ['paris', 'bruxelles'], length: 2, color: 'red', double: true },
    { id: 'par-fra-1', cities: ['paris', 'frankfurt'], length: 3, color: 'white' },
    { id: 'par-fra-2', cities: ['paris', 'frankfurt'], length: 3, color: 'orange', double: true },
    { id: 'pam-mad-1', cities: ['pamplona', 'madrid'], length: 3, color: 'black', isTunnel: true },
    { id: 'pam-mad-2', cities: ['pamplona', 'madrid'], length: 3, color: 'white', isTunnel: true, double: true },
    { id: 'pam-bar', cities: ['pamplona', 'barcelona'], length: 2, color: 'gray', isTunnel: true },
    { id: 'mad-lis', cities: ['madrid', 'lisbon'], length: 3, color: 'pink' },
    { id: 'mad-cad', cities: ['madrid', 'cadiz'], length: 3, color: 'orange' },
    { id: 'mad-bar', cities: ['madrid', 'barcelona'], length: 2, color: 'yellow' },
    { id: 'lis-cad', cities: ['lisbon', 'cadiz'], length: 2, color: 'blue' },
    { id: 'bar-mar', cities: ['barcelona', 'marseille'], length: 4, color: 'gray' },
    { id: 'fra-ess', cities: ['frankfurt', 'essen'], length: 2, color: 'green' },
    { id: 'fra-ber-1', cities: ['frankfurt', 'berlin'], length: 3, color: 'black' },
    { id: 'fra-ber-2', cities: ['frankfurt', 'berlin'], length: 3, color: 'red', double: true },
    { id: 'fra-mun', cities: ['frankfurt', 'munchen'], length: 2, color: 'pink' },
    { id: 'ess-ber', cities: ['essen', 'berlin'], length: 2, color: 'blue' },
    { id: 'ess-kob', cities: ['essen', 'kobenhavn'], length: 3, color: 'gray', isFerry: true },
    { id: 'ess-kob-2', cities: ['essen', 'kobenhavn'], length: 3, color: 'gray', isFerry: true, double: true },
    { id: 'kob-sto-1', cities: ['kobenhavn', 'stockholm'], length: 3, color: 'yellow' },
    { id: 'kob-sto-2', cities: ['kobenhavn', 'stockholm'], length: 3, color: 'white', double: true },
    { id: 'sto-pet', cities: ['stockholm', 'petrograd'], length: 8, color: 'gray' },
    { id: 'ber-dan', cities: ['berlin', 'danzig'], length: 4, color: 'gray' },
    { id: 'ber-war-1', cities: ['berlin', 'warszawa'], length: 4, color: 'pink' },
    { id: 'ber-war-2', cities: ['berlin', 'warszawa'], length: 4, color: 'yellow', double: true },
    { id: 'ber-wie', cities: ['berlin', 'wien'], length: 3, color: 'black' },
    { id: 'mun-wie', cities: ['munchen', 'wien'], length: 3, color: 'orange' },
    { id: 'mun-zur', cities: ['munchen', 'zurich'], length: 2, color: 'yellow', isTunnel: true },
    { id: 'mun-ven', cities: ['munchen', 'venezia'], length: 2, color: 'blue', isTunnel: true },
    { id: 'zur-par', cities: ['zurich', 'paris'], length: 3, color: 'gray', isTunnel: true },
    { id: 'zur-mar', cities: ['zurich', 'marseille'], length: 2, color: 'pink', isTunnel: true },
    { id: 'mar-ven', cities: ['marseille', 'venezia'], length: 2, color: 'gray', isTunnel: true },
    { id: 'mar-rom', cities: ['marseille', 'roma'], length: 4, color: 'gray', isTunnel: true },
    { id: 'ven-wie', cities: ['venezia', 'wien'], length: 2, color: 'gray' },
    { id: 'ven-zag', cities: ['venezia', 'zagrab'], length: 2, color: 'gray' },
    { id: 'ven-rom', cities: ['venezia', 'roma'], length: 2, color: 'black' },
    { id: 'rom-bri', cities: ['roma', 'brindisi'], length: 2, color: 'white' },
    { id: 'rom-pal', cities: ['roma', 'palermo'], length: 4, color: 'gray', isFerry: true },
    { id: 'pal-bri', cities: ['palermo', 'brindisi'], length: 3, color: 'gray', isFerry: true },
    { id: 'pal-ath', cities: ['palermo', 'athina'], length: 4, color: 'gray', isFerry: true },
    { id: 'bri-ath', cities: ['brindisi', 'athina'], length: 4, color: 'gray', isFerry: true },
    { id: 'dan-rig', cities: ['danzig', 'riga'], length: 3, color: 'black' },
    { id: 'dan-war', cities: ['danzig', 'warszawa'], length: 2, color: 'gray' },
    { id: 'rig-pet', cities: ['riga', 'petrograd'], length: 4, color: 'gray' },
    { id: 'rig-wil', cities: ['riga', 'wilno'], length: 4, color: 'green' },
    { id: 'wil-pet', cities: ['wilno', 'petrograd'], length: 4, color: 'blue' },
    { id: 'wil-mos', cities: ['wilno', 'moskva'], length: 4, color: 'yellow' },
    { id: 'wil-kyi', cities: ['wilno', 'kyiv'], length: 2, color: 'gray' },
    { id: 'wil-war', cities: ['wilno', 'warszawa'], length: 3, color: 'red' },
    { id: 'war-wie', cities: ['warszawa', 'wien'], length: 4, color: 'blue' },
    { id: 'war-kyi', cities: ['warszawa', 'kyiv'], length: 4, color: 'gray' },
    { id: 'kyi-bud', cities: ['kyiv', 'budapest'], length: 6, color: 'gray' },
    { id: 'kyi-buc', cities: ['kyiv', 'bucuresti'], length: 4, color: 'gray' },
    { id: 'kyi-kha', cities: ['kyiv', 'kharkov'], length: 4, color: 'gray' },
    { id: 'mos-kha', cities: ['moskva', 'kharkov'], length: 1, color: 'gray' },
    { id: 'mos-pet', cities: ['moskva', 'petrograd'], length: 4, color: 'white' },
    { id: 'kha-ros', cities: ['kharkov', 'rostov'], length: 2, color: 'gray' },
    { id: 'ros-soc', cities: ['rostov', 'sochi'], length: 2, color: 'gray' },
    { id: 'ros-sev', cities: ['rostov', 'sevastopol'], length: 4, color: 'gray' },
    { id: 'soc-erz', cities: ['sochi', 'erzurum'], length: 3, color: 'red' },
    { id: 'sev-buc', cities: ['sevastopol', 'bucuresti'], length: 4, color: 'white' },
    { id: 'sev-con', cities: ['sevastopol', 'constantinople'], length: 4, color: 'gray', isFerry: true },
    { id: 'buc-bud', cities: ['bucuresti', 'budapest'], length: 4, color: 'gray' },
    { id: 'buc-sof', cities: ['bucuresti', 'sofia'], length: 2, color: 'gray' },
    { id: 'buc-con', cities: ['bucuresti', 'constantinople'], length: 3, color: 'yellow' },
    { id: 'bud-wie-1', cities: ['budapest', 'wien'], length: 1, color: 'red' },
    { id: 'bud-wie-2', cities: ['budapest', 'wien'], length: 1, color: 'white', double: true },
    { id: 'bud-zag', cities: ['budapest', 'zagrab'], length: 2, color: 'orange' },
    { id: 'wie-zag', cities: ['wien', 'zagrab'], length: 2, color: 'gray' },
    { id: 'zag-sar', cities: ['zagrab', 'sarajevo'], length: 3, color: 'red' },
    { id: 'sar-sof', cities: ['sarajevo', 'sofia'], length: 2, color: 'gray' },
    { id: 'sar-ath', cities: ['sarajevo', 'athina'], length: 4, color: 'pink' },
    { id: 'sof-con', cities: ['sofia', 'constantinople'], length: 3, color: 'blue' },
    { id: 'sof-ath', cities: ['sofia', 'athina'], length: 3, color: 'gray' },
    { id: 'con-smy', cities: ['constantinople', 'smyrna'], length: 2, color: 'gray' },
    { id: 'con-ang', cities: ['constantinople', 'angora'], length: 2, color: 'gray', isTunnel: true },
    { id: 'smy-ang', cities: ['smyrna', 'angora'], length: 3, color: 'orange', isTunnel: true },
    { id: 'smy-ath', cities: ['smyrna', 'athina'], length: 2, color: 'gray', isFerry: true },
    { id: 'ang-erz', cities: ['angora', 'erzurum'], length: 3, color: 'black' },
  ]
};

export const NEW_YORK_MAP: MapData = {
  id: 'new-york',
  name: 'New York City',
  viewBox: '0 0 1000 1000',
  cities: [
    { id: 'harlem', name: 'Harlem', x: 500, y: 150 },
    { id: 'uws', name: 'Upper West Side', x: 400, y: 300 },
    { id: 'ues', name: 'Upper East Side', x: 600, y: 300 },
    { id: 'central-park', name: 'Central Park', x: 500, y: 300 },
    { id: 'times-square', name: 'Times Square', x: 500, y: 450 },
    { id: 'grand-central', name: 'Grand Central', x: 600, y: 400 },
    { id: 'empire-state', name: 'Empire State', x: 550, y: 550 },
    { id: 'gramercy', name: 'Gramercy', x: 600, y: 500 },
    { id: 'chelsea', name: 'Chelsea', x: 400, y: 550 },
    { id: 'east-village', name: 'East Village', x: 620, y: 620 },
    { id: 'greenwich', name: 'Greenwich Village', x: 450, y: 650 },
    { id: 'les', name: 'Lower East Side', x: 620, y: 720 },
    { id: 'soho', name: 'Soho', x: 480, y: 720 },
    { id: 'chinatown', name: 'Chinatown', x: 550, y: 750 },
    { id: 'wall-street', name: 'Wall Street', x: 500, y: 850 },
    { id: 'brooklyn-bridge', name: 'Brooklyn Bridge', x: 650, y: 850 },
    { id: 'statue-liberty', name: 'Statue of Liberty', x: 350, y: 950 },
  ],
  routes: [
    { id: 'har-cp', cities: ['harlem', 'central-park'], length: 2, color: 'black' },
    { id: 'cp-ts', cities: ['central-park', 'times-square'], length: 2, color: 'yellow' },
    { id: 'ts-gc', cities: ['times-square', 'grand-central'], length: 1, color: 'gray' },
    { id: 'gc-es', cities: ['grand-central', 'empire-state'], length: 2, color: 'pink' },
    { id: 'es-gra', cities: ['empire-state', 'gramercy'], length: 1, color: 'orange' },
    { id: 'gra-ev', cities: ['gramercy', 'east-village'], length: 2, color: 'blue' },
    { id: 'ev-les', cities: ['east-village', 'lower-east-side'], length: 1, color: 'red' },
    { id: 'les-chi', cities: ['les', 'chinatown'], length: 1, color: 'green' },
    { id: 'chi-ws', cities: ['chinatown', 'wall-street'], length: 2, color: 'black' },
    { id: 'ws-bb', cities: ['wall-street', 'brooklyn-bridge'], length: 2, color: 'gray', isFerry: true },
    { id: 'ws-sl', cities: ['wall-street', 'statue-liberty'], length: 4, color: 'gray', isFerry: true },
    { id: 'ts-che', cities: ['times-square', 'chelsea'], length: 2, color: 'blue' },
    { id: 'che-gv', cities: ['chelsea', 'greenwich'], length: 2, color: 'white' },
    { id: 'gv-so', cities: ['greenwich', 'soho'], length: 1, color: 'orange' },
    { id: 'so-chi', cities: ['soho', 'chinatown'], length: 1, color: 'yellow' },
    { id: 'uws-cp', cities: ['uws', 'central-park'], length: 2, color: 'green' },
    { id: 'ues-cp', cities: ['ues', 'central-park'], length: 2, color: 'red' },
    { id: 'uws-ts', cities: ['uws', 'times-square'], length: 3, color: 'black' },
    { id: 'ues-gc', cities: ['ues', 'grand-central'], length: 2, color: 'blue' },
  ]
};

export const ALL_MAPS = [EUROPE_MAP, NEW_YORK_MAP];
